<?php
// ThinkPHP 3.2.3 from abb20250919game; secrets stay outside the framework cache.
return [
    'MODULE_ALLOW_LIST' => ['Other', 'Admin'],
    'DEFAULT_MODULE' => 'Other',
    'DEFAULT_CONTROLLER' => 'Index',
    'DEFAULT_ACTION' => 'index',
    'URL_MODEL' => 0,
    'URL_CASE_INSENSITIVE' => true,
    'URL_ROUTER_ON' => false,
    'URL_PATHINFO_FETCH' => '',
    'APP_SUB_DOMAIN_DEPLOY' => false,
    'URL_PARAMS_BIND' => false,
    'CHECK_APP_DIR' => false,
    'SESSION_AUTO_START' => false,
    'REQUEST_VARS_FILTER' => false,
    'TMPL_ENGINE_TYPE' => 'PHP',
    'TMPL_TEMPLATE_SUFFIX' => '.php',
    'TMPL_DETECT_THEME' => false,
    'HTML_CACHE_ON' => false,
    'HTTP_CACHE_CONTROL' => 'no-store',
    'DEFAULT_TIMEZONE' => abbConfig()['timezone'],
    'SHOW_PAGE_TRACE' => false,
    'SHOW_ERROR_MSG' => false,
    'LOG_RECORD' => false,
    'TMPL_EXCEPTION_FILE' => __DIR__ . '/../View/error.php',
];
